services:
  github-runner:
    build: .
    restart: on-failure:5
    stop_grace_period: 5m
    environment:
      URL: ${URL}
      GITHUB_PAT: ${GITHUB_PAT}
      RUNNER_TOKEN: ${RUNNER_TOKEN}
      RUNNER_NAME: ${RUNNER_NAME}
      RUNNER_LABELS: ${RUNNER_LABELS}
    deploy:
      replicas: ${RUNNER_COUNT:-1}

volumes:
  runner-data:
